application: jackal-balanced
version: 8
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /other_tasks/clear_db
  script: clear_db.application3
  login: admin

- url: /cron_tasks/map_generator
  script: map_generator.application21
  login: admin

- url: /cron_tasks/old_map_generator
  script: old_map_generator.application22
  login: admin

- url: /stylesheets
  static_dir: stylesheets

- url: /fonts
  static_dir: fonts

- url: /main
  script: jackal_main.application

- url: /smth
  script: jackal_main.application

- url: /about
  script: jackal_main.application

- url: /test
  script: jackal_main.application

- url: /small_pics
  static_dir: small_pics

- url: /large_pics
  static_dir: large_pics

- url: /.*
  script: jackal_main.application


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
