application: jackal-balanced
version: 6
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /hello/world
  script: hello.application3

- url: /cron_tasks/map_generator
  script: map_generator.application2
  login: admin

- url: /stylesheets
  static_dir: stylesheets

- url: /main
  script: jackal_main.application

- url: /test
  script: jackal_main.application

- url: /small_pics
  static_dir: small_pics

- url: /.*
  script: jackal_main.application


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
