application: jackal-balanced
version: 5
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /cron_tasks/map_generator/
  script: map_generator.py

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  static_dir: small_pics

- url: /.*
  script: jackal_main.application


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
