application: bernarditos-guestbook
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  static_dir: pics
  
- url: /.*
  script: guestbook.application

libraries:
- name: webapp2
  version: latest
